name: CI

on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci
      - run: npm run lint


  cypress:
    runs-on: ubuntu-latest
    # needs: lint

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16

        - run: npm ci
        - run: npm run cypress || true
        - run: echo "Success" > result.txt
        
        - uses: actions/upload-artifact@v4
          with:
            path: result.txt
